### ISSUE TITLE
Allow changing uid/gid after binding

### ISSUE THREAD

**Issue by Kixunil** [steveklabnik/simple-server#103]
The problem: non-privileged users can't bind ports <1024 and port 80 is the standard port for HTTP. Running web server as root isn't good security practice. (Rust should be unexploitable, but who's willing to bet on it? :)) The standard way to solve it is to start as root and switch user after socket is bound.

There are three simple ways to allow it in `simple-server` without loss of generality:

* create `listen_with()` method, which works like `listen()`, but accepts a closure which is run after socket is bound
* create `listen_on()` method which accepts externally created socket
* move `TcpListener::bind` from `listen()` to `Server::new()`

If I had to choose, I'd probably choose `listen_on` approach, but I really don't care as long as it's implemented. I'm willing to make a PR, just tell me which approach do you prefer.

**Comment by steveklabnik** [comment]
Yeah, I haven't run into this because I'm always running nginx in front of simple-server. It'd be good to have the option, though.

>  accepts a closure which is run after socket is bound

I was considering changing listen's interface to be like this anyway; that's the way that the node API we copied works

> create listen_on() method which accepts externally created socket

I am merging https://github.com/steveklabnik/simple-server/pull/104 which does exactly this!

Maybe check that out and we'll see if it's what you want? I think it is though!

**Comment by Kixunil** [comment]
In my case nginx would be unnecessary complication. #104 solves the issue.
